/*
 * Copyright 2026-2026 the original author or authors.
 */

package io.modelcontextprotocol.spec.auth;

import java.net.URI;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.modelcontextprotocol.util.Assert;

/**
 * Represents an OAuth 2.0 Authorization Response per RFC 6749 and RFC 9207 (SEP-2468),
 * supporting validation of the {@code iss} (issuer) parameter to prevent OAuth mix-up
 * attacks in multi-authorization-server environments.
 *
 * @param code The authorization code returned by the authorization server.
 * @param state The state parameter returned by the authorization server.
 * @param iss The authorization server issuer identifier (RFC 9207 / SEP-2468).
 * @param error Error code if authorization failed.
 * @param errorDescription Human-readable error description if authorization failed.
 * @param errorUri URI identifying a human-readable web page with error information.
 * @author Model Context Protocol Authors
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OAuth2AuthorizationResponse(@JsonProperty("code") String code, @JsonProperty("state") String state,
		@JsonProperty("iss") String iss, @JsonProperty("error") String error,
		@JsonProperty("error_description") String errorDescription, @JsonProperty("error_uri") String errorUri) {

	@JsonCreator
	public OAuth2AuthorizationResponse {
	}

	public boolean isSuccess() {
		return this.code != null && this.error == null;
	}

	public boolean isError() {
		return this.error != null;
	}

	/**
	 * Validates the authorization response against the expected state and expected issuer
	 * per RFC 9207 and SEP-2468.
	 * @param expectedIssuer The expected authorization server issuer URL/identifier
	 * @param expectedState The expected state parameter previously generated by the
	 * client
	 * @return this response if validation succeeds
	 * @throws McpAuthorizationException if the response contains an error, state
	 * mismatches, or the issuer parameter is missing or mismatched
	 */
	public OAuth2AuthorizationResponse validate(String expectedIssuer, String expectedState) {
		if (this.error != null) {
			throw new McpAuthorizationException(this.error, this.errorDescription, "OAuth 2.0 authorization error: "
					+ this.error + (this.errorDescription != null ? " - " + this.errorDescription : ""));
		}

		if (expectedState != null) {
			if (this.state == null || !expectedState.equals(this.state)) {
				throw new McpAuthorizationException("invalid_state", null,
						"State parameter mismatch in authorization response: expected [" + expectedState
								+ "] but received [" + this.state + "]");
			}
		}

		if (expectedIssuer != null) {
			if (this.iss == null || this.iss.trim().isEmpty()) {
				throw new McpAuthorizationException("missing_issuer", null,
						"Missing required 'iss' parameter in authorization response per RFC 9207 / SEP-2468");
			}
			if (!normalizeIssuer(expectedIssuer).equals(normalizeIssuer(this.iss))) {
				throw new McpAuthorizationException("issuer_mismatch", null,
						"Authorization server issuer mismatch per RFC 9207 / SEP-2468: expected [" + expectedIssuer
								+ "] but received [" + this.iss + "]");
			}
		}

		return this;
	}

	private static String normalizeIssuer(String issuer) {
		if (issuer == null) {
			return "";
		}
		String trimmed = issuer.trim();
		if (trimmed.endsWith("/")) {
			return trimmed.substring(0, trimmed.length() - 1);
		}
		return trimmed;
	}

	/**
	 * Parse an authorization response from a redirect URI containing query or fragment
	 * parameters.
	 * @param redirectUri The redirect URI with authorization parameters
	 * @return Parsed {@link OAuth2AuthorizationResponse}
	 */
	public static OAuth2AuthorizationResponse fromUri(URI redirectUri) {
		Assert.notNull(redirectUri, "redirectUri must not be null");
		String query = redirectUri.getRawQuery();
		if (query == null || query.isEmpty()) {
			query = redirectUri.getRawFragment();
		}
		return fromQuery(query);
	}

	/**
	 * Parse an authorization response from a URL query string.
	 * @param query The raw query string
	 * @return Parsed {@link OAuth2AuthorizationResponse}
	 */
	public static OAuth2AuthorizationResponse fromQuery(String query) {
		if (query == null || query.isEmpty()) {
			return builder().build();
		}
		Map<String, String> params = new HashMap<>();
		String[] pairs = query.split("&");
		for (String pair : pairs) {
			int idx = pair.indexOf("=");
			if (idx > 0) {
				String key = URLDecoder.decode(pair.substring(0, idx), StandardCharsets.UTF_8);
				String value = (idx < pair.length() - 1)
						? URLDecoder.decode(pair.substring(idx + 1), StandardCharsets.UTF_8) : "";
				params.put(key, value);
			}
		}
		return fromParameters(params);
	}

	/**
	 * Create an authorization response from a parameter map.
	 * @param parameters The map of parameters
	 * @return Parsed {@link OAuth2AuthorizationResponse}
	 */
	public static OAuth2AuthorizationResponse fromParameters(Map<String, String> parameters) {
		Assert.notNull(parameters, "parameters must not be null");
		return builder().code(parameters.get("code"))
			.state(parameters.get("state"))
			.iss(parameters.get("iss"))
			.error(parameters.get("error"))
			.errorDescription(parameters.get("error_description"))
			.errorUri(parameters.get("error_uri"))
			.build();
	}

	public static Builder builder() {
		return new Builder();
	}

	public static final class Builder {

		private String code;

		private String state;

		private String iss;

		private String error;

		private String errorDescription;

		private String errorUri;

		public Builder code(String code) {
			this.code = code;
			return this;
		}

		public Builder state(String state) {
			this.state = state;
			return this;
		}

		public Builder iss(String iss) {
			this.iss = iss;
			return this;
		}

		public Builder error(String error) {
			this.error = error;
			return this;
		}

		public Builder errorDescription(String errorDescription) {
			this.errorDescription = errorDescription;
			return this;
		}

		public Builder errorUri(String errorUri) {
			this.errorUri = errorUri;
			return this;
		}

		public OAuth2AuthorizationResponse build() {
			return new OAuth2AuthorizationResponse(this.code, this.state, this.iss, this.error, this.errorDescription,
					this.errorUri);
		}

	}

}
